defaults:
  run:
    shell: bash .github/workflows/logger.sh {0}
name: CI Pipeline
on:
  workflow_dispatch:
    inputs:
      build-deploy:
        description: "O que deseja fazer?"
        required: false
        default: Somente Build
        type: choice
        options:
          - Somente Build
          - Build + Deploy
          - Atualizacao values.yaml
      enabled-fortify:
        description: "Habilitar Fortify SAST"
        required: false
        default: true
        type: boolean
      enabled-sonar:
        description: "Habilitar testes Sonarqube"
        required: false
        default: true
        type: boolean
      enabled-acs:
        description: "Habilitar Scan de Imagem ACS"
        required: false
        default: true
        type: boolean
      enabled-mend:
        description: "Habilitar Scan Mend"
        required: true
        default: true
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compile Code
        run: echo "Compilando..."
      - name: Run Unit Tests
        run: echo "Rodando testes..."

  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Fortify Analysis
        run: |
          echo "Iniciando scan..."
          sleep 2
